package mainStat;

import java.util.Arrays;

/**
 * klasse stellt methoden zur ausgabe von histogrammen
 * auf der console zur verfügung.
 */
public class printStatistik {
    /**
     * methode gibt beim aufruf Ordnungstatistik
     * als Histogramm Vertikal aus
     */
    public static void klssStatVert() {
        for (int i = 0; i < getValues.klssArr.length; i++) {

            if (getValues.klssArr[i].x != 0) { // lässt leere Index.pos aus

                System.out.print(( ("|Kj"+ (i+1)+  "|="+
                        getValues.klssArr[i].y) + ": "));
                for (int k = 0; k < getValues.klssArr[i].y; k++) {
                    System.out.print("*");
                }
                System.out.println();
            }
        }
    }
    /**
     * methode gibt beim aufruf Ordnungstatistik
     * als Histogramm Horizontal aus
     */
    public static void klssStatHori() {

        /* point array übersetzen inn int array */
        int p= getValues.sizeFRAME;
        int[] counts= new int[getValues.klssArr.length];
        for (int x= 0; x< counts.length; x++) { // TODO EXCEPTION
            int i= getValues.klssArr[x].y;
            counts[x]= i;
        }
        /*int array wird zur 2D array umgewandelt für histogramm*/
        char[][] histoMap= getArrayHorizontal(counts);

        for (int i=0; i< histoMap.length; i++) {
            char[] row= histoMap[i];
            if ( i > 35) {
                System.out.print("0"+(histoMap.length-i)+" | ");
            } else {
                System.out.print((histoMap.length-i)+" | ");
            }
                                                                // TODO ask somebody
                                              // entferne satement, ordnung weg?!?!?!
            for (int j=row.length-1; j>= 0; j--) {
                    if (row[j] == '*') {
                        System.out.print("\t*");
                    } else if (row[j] != '*') {
                        System.out.print("\t");
                    }
                }
            System.out.print("\n");
            }
        System.out.print("00 |Kj ");
       for (int g=getValues.klssArr.length-1; g>= 0; g--) {
           System.out.print((getValues.klssArr.length-g)+"  ");
       }
       System.out.println();
       // TODO print klssrange
    }

    /**
     * @method called by <klssStatHori>, to get 2D Array of Int
     * @param arr   int array generated by getValues.getArrays
     * @return 2D char array which now will print out from bottom
     *                 to top with '*'
     */
    public static char[][] getArrayHorizontal(int[] arr) { // TODO
        int biggest= 0;
        for (int e= 0; e< arr.length; e++) {
            if (arr[e] > biggest){
                biggest= arr[e];
            }
        }
        char[][] map= new char [biggest+1][arr.length]; // y,x karte
        for (int y=0; y< biggest-1; y++) {				//
            Arrays.fill(map[y], ' ');							// init map with '0'
        }
        for (int x= arr.length-1; x>= 0; x--) {
            int diff= biggest- arr[x] ;
            for (int y= biggest; y> diff; y--) {
                map[y][x]= '*';
            }
        }
        return map;
    }

    /**
     * methode gibt beim aufruf Ordnungstatistik
     * als Histogramm Vertikal aus
     */
    public static void ordStatVert() {
        for (int i = 0; i < getValues.ordArr.length; i++) {

            if (getValues.ordArr[i].x != 0) { // lässt leere Index.pos aus

                if ( i < 10) {
                    System.out.print(" ");
                }
                System.out.print( i + ": ");
                for (int k = 0; k < getValues.ordArr[i].x; k++) {
                    System.out.print("*");
                }
                System.out.println();
            }
        }

    }
}
